apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-eureka-server-deployment
  labels:
    app: spring-eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-eureka-server
  template:
    metadata:
      labels:
        app: spring-eureka-server
    spec:
      containers:
      - name: spring-eureka-server
        image: spring-eureka-server:v1
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: spring-eureka-server
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761